configuration: Release

build:
  verbosity: minimal
  publish_wap: true 
  
artifacts:
  - path: AnimCmd/bin/Release
    name: AnimCmd
  
after_build:
  - appveyor PushArtifact AnimCmd\bin\AnimCmd.zip -FileName Downloads\dev\AnimCmd.zip -DeploymentName test
  
deploy:
  - provider: FTP
    host: animcmd.net16.net
    protocol: ftp
    username: a2743571
    password:
      secure: XDMi7RoQ6O8Mx+fPKLafCQ==
    folder: Downloads/dev
    artifact: AnimCmd
